* Полдень. Стругацкие
2/10
01.01.2020  
начал и не осилил даже пары часов. Это ужасно. Представления о людях - привет из 50-х. Слишком много мыслешума разных людей, странные технические особенности.
Выкинул эту фигню.  

* Основание 2
Азимов
9/10
14.01.2020
Прям хорошо, надо было начинать читать по хронологии, теперь хочу перечитать осн. трилогию, но с другой стороны интереснее чем все это продолжилось
* Стальные пещеры
Азимов
9/10
16.01.2020
Небольшой рассказик вводящий в мир роботов и открывающий взор в космос

* Обнаженное солнце
Азимов
17.01.2020

* Роботы зари
Азимов
18.01.2020

* Роботы и империя
Азимов
26.01.2020
Как сериал - супер

* Гиперион
28.04.2020
2/10 - вода в ступе, никакая технологи. оборваный конец. Читать дальше не хочется.

* Трилогия марса
Робинсон
27.05.2020
8/10 - очень неплохое. Под конец немного затянуто.

* Чудотворец из вшивого тупика
03.06.2020
7/10 художка. очень короткий. норм, но я чет люблю подлиннее

* Хаос. Придумывая науку
05.06.2020
6/10 Не очень, но тема прикольная

* Основание. Кризис
17.06.2020
8/10 

* Основание. Земля
08.07.2020
6/10 Просто родмуви

* Лесница в небо. 
Хазин
27.07.2020
8/10 Прям хорошо. Полезная

* Экспансия. Пробуждение левиафана
15.08.2020
9/10 
Хотя я и смотрел сериал, а он идет копейка в копейку. Читать было захватывающе интересно.
А еще я узнал, что у меня только 4 книги из 9.

* Воспоминания о будущем
Хазин
12.09.2020
8/10 Хорошо.

* Экспансия 3
19.09.2020
7/10 Уже видел, надо дочитать 4 и переходить к еще неэкранизированным частям

* Экспансия 4
24.09.2020
7/10

* Экспансия 5
27.09.2020
8/10


